<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">$(MSBuildThisFileDirectory)project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\Tea\.nuget\packages\</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">6.11.2</NuGetToolVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <SourceRoot Include="C:\Users\Tea\.nuget\packages\" />
  </ItemGroup>
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <PkgActiproSoftware_Controls_WPF_Shared Condition=" '$(PkgActiproSoftware_Controls_WPF_Shared)' == '' ">C:\Users\Tea\.nuget\packages\actiprosoftware.controls.wpf.shared\25.1.1</PkgActiproSoftware_Controls_WPF_Shared>
    <PkgActiproSoftware_Controls_WPF_SyntaxEditor Condition=" '$(PkgActiproSoftware_Controls_WPF_SyntaxEditor)' == '' ">C:\Users\Tea\.nuget\packages\actiprosoftware.controls.wpf.syntaxeditor\25.1.1</PkgActiproSoftware_Controls_WPF_SyntaxEditor>
  </PropertyGroup>
</Project>